"""Autonomous task ratio measurement.

Classifies run_log entries as autonomous (generated by OODA, goal planner,
event bus, or self-improve) vs static (from campaign YAML). Measures progress
toward the self-sustaining-autonomy goal (>50% autonomous tasks).
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

# Task field prefixes that indicate autonomous generation
AUTONOMOUS_PREFIXES = (
    "[ooda]",
    "[goal]",
    "[event]",
    "[reactive]",
    "[self-improve]",
)

# RunLogEntry.source values that indicate autonomous origin
AUTONOMOUS_SOURCES = ("ooda", "goals", "events", "reactive")


def _is_autonomous(entry: dict) -> bool:
    """Check if a run log entry represents an autonomous task."""
    task = entry.get("task", "").lower()
    if any(task.startswith(prefix) for prefix in AUTONOMOUS_PREFIXES):
        return True
    source = entry.get("source", "campaign")
    if source in AUTONOMOUS_SOURCES:
        return True
    return False


def autonomous_task_ratio(run_log_path: Path) -> dict:
    """Analyze run_log.jsonl and return autonomous vs static task breakdown.

    Returns:
        dict with keys: total (int), autonomous (int), static (int),
        ratio (float 0.0-1.0), by_source (dict[str, int]).
    """
    if not run_log_path.exists():
        return {"total": 0, "autonomous": 0, "static": 0, "ratio": 0.0, "by_source": {}}

    total = 0
    autonomous = 0
    by_source: dict[str, int] = {}

    try:
        with open(run_log_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                total += 1
                source = entry.get("source", "campaign")
                by_source[source] = by_source.get(source, 0) + 1
                if _is_autonomous(entry):
                    autonomous += 1
    except OSError as e:
        log.error("Failed to read run log for ratio analysis: %s", e)
        return {"total": 0, "autonomous": 0, "static": 0, "ratio": 0.0, "by_source": {}}

    static = total - autonomous
    ratio = autonomous / total if total > 0 else 0.0

    return {
        "total": total,
        "autonomous": autonomous,
        "static": static,
        "ratio": ratio,
        "by_source": by_source,
    }


def format_ratio_summary(stats: dict) -> str:
    """Format autonomous ratio stats as a human-readable string."""
    total = stats.get("total", 0)
    autonomous = stats.get("autonomous", 0)
    ratio = stats.get("ratio", 0.0)
    if total == 0:
        return "Autonomous ratio: no tasks recorded yet"
    return f"Autonomous: {autonomous}/{total} ({ratio:.1%})"


def format_detailed_summary(stats: dict) -> str:
    """Format a detailed breakdown including source distribution."""
    lines = [format_ratio_summary(stats)]
    by_source = stats.get("by_source", {})
    if by_source:
        lines.append("  By source:")
        for source, count in sorted(by_source.items(), key=lambda x: -x[1]):
            pct = count / stats["total"] * 100 if stats["total"] > 0 else 0
            lines.append(f"    {source}: {count} ({pct:.0f}%)")
    goal_met = stats.get("ratio", 0) >= 0.5
    lines.append(f"  Goal (>50%): {'MET' if goal_met else 'NOT MET'}")
    return "\n".join(lines)
