"""TextGrad-powered evolved prompt generation from failed traces.

This module implements TextGrad-style prompt optimization:
1. Collect failed task traces (from run_log.jsonl)
2. Analyze failure patterns using an LLM (Claude Haiku)
3. Generate evolved prompt variants with reasoning
4. Log variants to data/textgrad_evolved_prompts.jsonl

Key insight: Feed *traces* (what went wrong) + *current prompt* to an LLM
to generate concrete prompt mutations that address specific failure modes.

Reference: TextGrad (https://arxiv.org/abs/2406.12841) — use LLM feedback
on failures to improve system prompts iteratively.
"""
from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4

log = logging.getLogger("secretary.textgrad_evolution")


# ── Data structures ──────────────────────────────────────────────────────

@dataclass
class PromptVariant:
    """An evolved prompt variant generated by TextGrad analysis."""

    variant_id: str = field(default_factory=lambda: f"var-{uuid4().hex[:12]}")
    index: int = 0  # Position in variants list (1-indexed in output)
    original_prompt: str = ""
    evolved_prompt: str = ""
    task_category: str = ""
    reasoning: str = ""
    changes_summary: str = ""
    confidence: float = 0.0  # 0.0-1.0 estimated improvement probability
    expected_improvement_areas: list[str] = field(default_factory=list)
    risks: list[str] = field(default_factory=list)
    source_traces: list[str] = field(default_factory=list)  # task_ids analyzed

    def to_dict(self) -> dict[str, Any]:
        """Convert to JSON-serializable dict."""
        return asdict(self)


@dataclass
class PromptEvolutionRound:
    """A complete TextGrad analysis round."""

    round_id: str = field(default_factory=lambda: f"round-{uuid4().hex[:12]}")
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    original_prompt: str = ""
    variants: list[PromptVariant] = field(default_factory=list)
    num_traces_analyzed: int = 0
    meta_analysis: str = ""  # Summary of common failure patterns

    def to_dict(self) -> dict[str, Any]:
        """Convert to JSON-serializable dict."""
        return {
            "round_id": self.round_id,
            "timestamp": self.timestamp,
            "original_prompt": self.original_prompt,
            "variants": [v.to_dict() for v in self.variants],
            "num_traces_analyzed": self.num_traces_analyzed,
            "meta_analysis": self.meta_analysis,
        }


# ── Trace analysis ──────────────────────────────────────────────────────

def _format_traces_for_analysis(traces: list[dict[str, Any]]) -> str:
    """Format failed traces into a structured prompt for meta-analysis."""
    if not traces:
        return "(no traces provided)"

    parts = []
    for i, trace in enumerate(traces, 1):
        parts.append(f"FAILURE #{i}:")
        parts.append(f"  Task ID: {trace.get('task_id', 'unknown')}")
        parts.append(f"  Judge Score: {trace.get('judge_score', '?')}/1.0")
        parts.append(f"  Reason: {trace.get('judge_reason', '(no reason)')}")
        parts.append(f"  Category: {trace.get('category', '?')}")
        if trace.get('response_text'):
            lines = trace['response_text'].split('\n')[:3]  # First 3 lines
            parts.append(f"  Response Preview: {' '.join(lines[:100])}")
        parts.append("")

    return "\n".join(parts)


def _extract_failure_patterns(traces: list[dict[str, Any]]) -> str:
    """Extract common failure patterns from traces."""
    if not traces:
        return "(no patterns detected)"

    patterns: dict[str, int] = {}
    keywords = {
        "paralleliz": "Tool parallelization / sequential execution",
        "output.*timing": "Output at wrong turn / premature text",
        "tool.*call": "Insufficient tool calls / missing tools",
        "test": "Missing verification / test execution",
        "incomplete": "Incomplete task / partial solution",
        "rule": "Rule violation / constraint not followed",
        "turn": "Turn-based rule violation",
    }

    for trace in traces:
        reason = trace.get("judge_reason", "").lower()
        for keyword, pattern_name in keywords.items():
            if re.search(keyword, reason):
                patterns[pattern_name] = patterns.get(pattern_name, 0) + 1

    if not patterns:
        return "(generic failures, no specific pattern detected)"

    sorted_patterns = sorted(patterns.items(), key=lambda x: -x[1])
    return "\n".join(f"- {name}: {count} traces" for name, count in sorted_patterns)


# ── Evolved prompt generation (requires LLM API) ───────────────────────

_META_PROMPT_TEMPLATE = """\
You are a prompt evolution expert. Given a system prompt and examples of how it failed,
generate 2-3 improved variants that address the root causes.

CURRENT SYSTEM PROMPT:
```
{original_prompt}
```

FAILURE ANALYSIS (traces from recent runs):
{traces_formatted}

COMMON FAILURE PATTERNS:
{patterns}

TASK: Generate 2 evolved prompt variants that:
1. Keep the original intent and structure
2. Explicitly address the identified failure patterns
3. Include specific changes from the failure analysis

For EACH variant, provide:
- **Evolved Prompt**: [full prompt text, ~{prompt_length} words]
- **Reasoning**: [Why this addresses failures X, Y, Z]
- **Changes Summary**: [Bullet list of specific changes]
- **Confidence**: [0.0-1.0 estimated improvement probability]
- **Expected Improvements**: [which areas will improve]
- **Risks**: [potential negative effects]

Format as JSON array with keys:
  evolved_prompt, reasoning, changes_summary, confidence, expected_improvements, risks

IMPORTANT:
- Be specific about which failure traces each change addresses
- Confidence should be realistic (0.5-0.9 range for substantial mutations)
- Changes should be actionable and concrete
"""


def _call_textgrad_llm(
    original_prompt: str,
    traces: list[dict[str, Any]],
    base_url: str,
    model: str = "claude-haiku-4.5",
) -> list[dict[str, Any]] | None:
    """Call Claude to generate evolved prompts.

    Args:
        original_prompt: Current system prompt
        traces: List of failed task traces
        base_url: LLM API base URL (e.g., "http://localhost:8000")
        model: Model to use (default: claude-haiku-4.5)

    Returns:
        List of variant dicts (evolved_prompt, reasoning, etc.) or None on error
    """
    try:
        import httpx
    except ImportError:
        log.warning("httpx not available; skipping LLM call")
        return None

    traces_formatted = _format_traces_for_analysis(traces)
    patterns = _extract_failure_patterns(traces)
    prompt_length = len(original_prompt.split())

    meta_prompt = _META_PROMPT_TEMPLATE.format(
        original_prompt=original_prompt,
        traces_formatted=traces_formatted,
        patterns=patterns,
        prompt_length=prompt_length,
    )

    payload = {
        "model": model,
        "messages": [
            {"role": "user", "content": meta_prompt}
        ],
        "temperature": 0.7,
        "max_tokens": 2048,
    }

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                f"{base_url}/v1/messages",
                json=payload,
                headers={"Content-Type": "application/json"},
            )
            response.raise_for_status()
            result = response.json()
    except Exception as exc:
        log.warning("LLM API call failed: %s", exc)
        return None

    # Extract response text
    if "content" not in result or not result["content"]:
        log.warning("LLM response missing content")
        return None

    response_text = result["content"][0].get("text", "")
    if not response_text:
        log.warning("LLM response empty")
        return None

    # Parse JSON from response
    try:
        # Try to extract JSON array from markdown code block
        json_match = re.search(r"```(?:json)?\s*(\[.*?\])\s*```", response_text, re.DOTALL)
        if json_match:
            variants_json = json.loads(json_match.group(1))
        else:
            # Try direct JSON parse
            variants_json = json.loads(response_text)

        if not isinstance(variants_json, list):
            variants_json = [variants_json]

        return variants_json
    except (json.JSONDecodeError, AttributeError) as exc:
        log.warning("Failed to parse LLM response as JSON: %s", exc)
        log.debug("Response text:\n%s", response_text[:500])
        return None


def generate_evolved_prompts(
    original_prompt: str,
    traces: list[dict[str, Any]],
    base_url: str,
    category: str = "general",
    model: str = "claude-haiku-4.5",
) -> PromptEvolutionRound | None:
    """Generate evolved prompt variants from failed traces.

    Steps:
    1. Format traces for analysis
    2. Call LLM to generate variants
    3. Parse and validate responses
    4. Create PromptEvolutionRound with variants

    Args:
        original_prompt: Current system prompt to evolve
        traces: List of failed task traces (dict with judge_reason, etc.)
        base_url: LLM API base URL
        category: Task category (email, calendar, file, etc.)
        model: LLM model to use

    Returns:
        PromptEvolutionRound with 2+ variants, or None on error
    """
    log.info("Starting TextGrad evolution: analyzing %d traces", len(traces))

    # Get evolved variants from LLM
    variants_raw = _call_textgrad_llm(
        original_prompt=original_prompt,
        traces=traces,
        base_url=base_url,
        model=model,
    )

    if not variants_raw or len(variants_raw) < 2:
        log.warning("LLM returned fewer than 2 variants")
        return None

    # Convert to PromptVariant objects
    variants = []
    task_ids = [t.get("task_id", "") for t in traces]

    for idx, raw_variant in enumerate(variants_raw[:3], 1):  # Limit to 3
        try:
            variant = PromptVariant(
                variant_id=f"var-{uuid4().hex[:12]}",
                index=idx,
                original_prompt=original_prompt,
                evolved_prompt=raw_variant.get("evolved_prompt", ""),
                task_category=category,
                reasoning=raw_variant.get("reasoning", ""),
                changes_summary=raw_variant.get("changes_summary", ""),
                confidence=float(raw_variant.get("confidence", 0.7)),
                expected_improvement_areas=raw_variant.get("expected_improvements", []),
                risks=raw_variant.get("risks", []),
                source_traces=task_ids,
            )
            if variant.evolved_prompt and variant.reasoning:
                variants.append(variant)
        except Exception as exc:
            log.warning("Failed to convert variant %d: %s", idx, exc)
            continue

    if len(variants) < 2:
        log.error("Failed to generate 2+ valid variants")
        return None

    # Create evolution round
    patterns = _extract_failure_patterns(traces)
    round_obj = PromptEvolutionRound(
        round_id=f"round-{uuid4().hex[:12]}",
        timestamp=datetime.now(timezone.utc).isoformat(),
        original_prompt=original_prompt,
        variants=variants,
        num_traces_analyzed=len(traces),
        meta_analysis=patterns,
    )

    log.info("Generated %d evolved variants", len(variants))
    return round_obj


# ── Persistence ──────────────────────────────────────────────────────────

def save_evolution_round(
    round_obj: PromptEvolutionRound,
    output_path: Path,
) -> None:
    """Append evolution round to JSONL file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(round_obj.to_dict()))
        f.write("\n")

    log.info("Saved evolution round %s to %s", round_obj.round_id, output_path)


def load_evolution_rounds(
    output_path: Path,
) -> list[PromptEvolutionRound]:
    """Load all evolution rounds from JSONL file."""
    if not output_path.exists():
        return []

    rounds = []
    try:
        with open(output_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    data = json.loads(line)
                    variants = [
                        PromptVariant(**v) for v in data.get("variants", [])
                    ]
                    round_obj = PromptEvolutionRound(
                        round_id=data["round_id"],
                        timestamp=data["timestamp"],
                        original_prompt=data["original_prompt"],
                        variants=variants,
                        num_traces_analyzed=data.get("num_traces_analyzed", 0),
                        meta_analysis=data.get("meta_analysis", ""),
                    )
                    rounds.append(round_obj)
    except Exception as exc:
        log.warning("Error loading evolution rounds: %s", exc)

    return rounds


# ── Reporting ───────────────────────────────────────────────────────────

def format_evolution_report(round_obj: PromptEvolutionRound) -> str:
    """Format evolution round as human-readable report."""
    lines = []
    lines.append("\n" + "=" * 80)
    lines.append("TEXTGRAD PROMPT EVOLUTION REPORT")
    lines.append("=" * 80)
    lines.append(f"Round ID: {round_obj.round_id}")
    lines.append(f"Timestamp: {round_obj.timestamp}")
    lines.append(f"Traces Analyzed: {round_obj.num_traces_analyzed}")
    lines.append(f"Variants Generated: {len(round_obj.variants)}")
    lines.append("")

    lines.append("FAILURE PATTERNS IDENTIFIED:")
    lines.append(round_obj.meta_analysis)
    lines.append("")

    for variant in round_obj.variants:
        lines.append(f"{'─' * 80}")
        lines.append(f"VARIANT {variant.index} (ID: {variant.variant_id})")
        lines.append(f"Confidence: {variant.confidence:.2f}")
        lines.append("")

        lines.append("Reasoning:")
        lines.append(f"  {variant.reasoning}")
        lines.append("")

        lines.append("Changes Summary:")
        for change_line in variant.changes_summary.split("\n"):
            if change_line.strip():
                lines.append(f"  {change_line}")
        lines.append("")

        if variant.expected_improvement_areas:
            lines.append("Expected Improvements:")
            for area in variant.expected_improvement_areas:
                lines.append(f"  • {area}")
            lines.append("")

        if variant.risks:
            lines.append("Risks:")
            for risk in variant.risks:
                lines.append(f"  ⚠ {risk}")
            lines.append("")

        # Show evolved prompt (truncated)
        evolved_preview = variant.evolved_prompt[:200] + "..." if len(variant.evolved_prompt) > 200 else variant.evolved_prompt
        lines.append("Evolved Prompt Preview:")
        lines.append(f"  {evolved_preview}")
        lines.append("")

    lines.append("=" * 80 + "\n")
    return "\n".join(lines)


# ── Experiment configuration ──────────────────────────────────────────────

def variant_to_experiment_config(variant: PromptVariant) -> dict[str, Any]:
    """Convert a variant to autoresearch experiment config."""
    return {
        "name": f"textgrad-{variant.variant_id}",
        "system_prompt": variant.evolved_prompt,
        "variant_id": variant.variant_id,
        "source_variant_index": variant.index,
        "reasoning": variant.reasoning,
        "confidence": variant.confidence,
        "expected_improvements": variant.expected_improvement_areas,
        "risks": variant.risks,
    }


__all__ = [
    "PromptVariant",
    "PromptEvolutionRound",
    "generate_evolved_prompts",
    "save_evolution_round",
    "load_evolution_rounds",
    "format_evolution_report",
    "variant_to_experiment_config",
]
